project_id = "norpnhvszwfbwqmvwmlf"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.test-card-charge]
    verify_jwt = false
  [functions.rebill-cards]
    verify_jwt = false
  [functions.reconcile-pix-payments]
    verify_jwt = false
